name: "example_for_generator"
description: example
version: 0.0.1
homepage: https://github.com

environment: 
  sdk: ">=2.12.0 <4.0.0"

flutter:
  assets:
    - images/
    - assets/

    - path: assets/red/
      flavors:
        - red    
